// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/test/v1/foo.proto

package testv1

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Foo presents the foo.
type Foo struct {
	Int32                int32    `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64                int64    `protobuf:"varint,2,opt,name=int64,proto3" json:"int64,omitempty"`
	Float                float32  `protobuf:"fixed32,3,opt,name=float,proto3" json:"float,omitempty"`
	Double               float64  `protobuf:"fixed64,4,opt,name=double,proto3" json:"double,omitempty"`
	Uint32               uint32   `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64               uint64   `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Bool                 bool     `protobuf:"varint,7,opt,name=bool,proto3" json:"bool,omitempty"`
	Bytes                []byte   `protobuf:"bytes,8,opt,name=bytes,proto3" json:"bytes,omitempty"`
	String_              string   `protobuf:"bytes,9,opt,name=string,proto3" json:"string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ccc3b9c1ba4daef, []int{0}
}
func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *Foo) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *Foo) GetFloat() float32 {
	if m != nil {
		return m.Float
	}
	return 0
}

func (m *Foo) GetDouble() float64 {
	if m != nil {
		return m.Double
	}
	return 0
}

func (m *Foo) GetUint32() uint32 {
	if m != nil {
		return m.Uint32
	}
	return 0
}

func (m *Foo) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

func (m *Foo) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Foo) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Foo) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func init() {
	proto.RegisterType((*Foo)(nil), "test.v1.Foo")
}

func init() { proto.RegisterFile("proto/test/v1/foo.proto", fileDescriptor_5ccc3b9c1ba4daef) }

var fileDescriptor_5ccc3b9c1ba4daef = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xd0, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0x61, 0x5d, 0x93, 0xb8, 0xa9, 0x81, 0xc5, 0x42, 0x70, 0xe3, 0xc1, 0x74, 0x53, 0xa2,
	0xd0, 0xaa, 0x0f, 0xd0, 0xa1, 0x73, 0x75, 0x23, 0x1b, 0x86, 0x14, 0x55, 0x0a, 0x3d, 0xd4, 0xb8,
	0x91, 0x78, 0x4c, 0xde, 0x08, 0x39, 0x36, 0x9b, 0xbf, 0x7f, 0x38, 0xeb, 0xce, 0x3e, 0x7e, 0x5f,
	0x34, 0x68, 0x1b, 0xfa, 0x31, 0xb4, 0x53, 0xd7, 0x1e, 0x55, 0x9b, 0xb9, 0xb8, 0x65, 0x4c, 0xcd,
	0xd4, 0x3d, 0xff, 0x82, 0x2d, 0xf6, 0xaa, 0xee, 0xde, 0x56, 0xa7, 0x73, 0x58, 0xbf, 0x20, 0x10,
	0x70, 0x25, 0x09, 0xb9, 0x6e, 0x37, 0xb8, 0x20, 0xe0, 0x42, 0x12, 0x62, 0x3d, 0x0e, 0xfa, 0x16,
	0xb0, 0x20, 0xe0, 0x85, 0x24, 0xb8, 0x07, 0x6b, 0x3e, 0xf4, 0xea, 0x87, 0x1e, 0x4b, 0x02, 0x06,
	0xc9, 0x8a, 0xfd, 0x9a, 0x46, 0x57, 0x04, 0x7c, 0x27, 0x59, 0xff, 0x7d, 0xbb, 0x41, 0x43, 0xc0,
	0xa5, 0x64, 0x39, 0x67, 0x4b, 0xaf, 0x3a, 0xe0, 0x92, 0x80, 0x6b, 0x99, 0xdf, 0xf1, 0x47, 0xff,
	0x13, 0xfa, 0x11, 0x6b, 0x02, 0xbe, 0x95, 0x84, 0x38, 0x61, 0x0c, 0x97, 0xd3, 0xf9, 0x13, 0x57,
	0x04, 0xbc, 0x92, 0xac, 0xdd, 0x93, 0xbd, 0x79, 0xd7, 0xaf, 0x26, 0xaf, 0xb8, 0xab, 0xf7, 0xaa,
	0x87, 0xb8, 0xf5, 0x01, 0x5e, 0x4d, 0x8c, 0x53, 0xe7, 0xcd, 0x7c, 0x86, 0xf5, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0xf0, 0x6c, 0x00, 0x21, 0x01, 0x00, 0x00,
}
