// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/test/v1/test.proto

package testv1

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Test presents the test.
type Test struct {
	Int32                int32    `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64                int64    `protobuf:"varint,2,opt,name=int64,proto3" json:"int64,omitempty"`
	Float                float32  `protobuf:"fixed32,3,opt,name=float,proto3" json:"float,omitempty"`
	Double               float64  `protobuf:"fixed64,4,opt,name=double,proto3" json:"double,omitempty"`
	Uint32               uint32   `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64               uint64   `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Bool                 bool     `protobuf:"varint,7,opt,name=bool,proto3" json:"bool,omitempty"`
	Bytes                []byte   `protobuf:"bytes,8,opt,name=bytes,proto3" json:"bytes,omitempty"`
	String_              string   `protobuf:"bytes,9,opt,name=string,proto3" json:"string,omitempty"`
	Test2                *Test2   `protobuf:"bytes,10,opt,name=test2,proto3" json:"test2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_81db44fc9bdef0bb, []int{0}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *Test) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *Test) GetFloat() float32 {
	if m != nil {
		return m.Float
	}
	return 0
}

func (m *Test) GetDouble() float64 {
	if m != nil {
		return m.Double
	}
	return 0
}

func (m *Test) GetUint32() uint32 {
	if m != nil {
		return m.Uint32
	}
	return 0
}

func (m *Test) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

func (m *Test) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Test) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Test) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *Test) GetTest2() *Test2 {
	if m != nil {
		return m.Test2
	}
	return nil
}

type Test2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test2) Reset()         { *m = Test2{} }
func (m *Test2) String() string { return proto.CompactTextString(m) }
func (*Test2) ProtoMessage()    {}
func (*Test2) Descriptor() ([]byte, []int) {
	return fileDescriptor_81db44fc9bdef0bb, []int{1}
}
func (m *Test2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test2.Unmarshal(m, b)
}
func (m *Test2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test2.Marshal(b, m, deterministic)
}
func (m *Test2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test2.Merge(m, src)
}
func (m *Test2) XXX_Size() int {
	return xxx_messageInfo_Test2.Size(m)
}
func (m *Test2) XXX_DiscardUnknown() {
	xxx_messageInfo_Test2.DiscardUnknown(m)
}

var xxx_messageInfo_Test2 proto.InternalMessageInfo

func (m *Test2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "test.v1.Test")
	proto.RegisterType((*Test2)(nil), "test.v1.Test2")
}

func init() { proto.RegisterFile("proto/test/v1/test.proto", fileDescriptor_81db44fc9bdef0bb) }

var fileDescriptor_81db44fc9bdef0bb = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xc1, 0x6a, 0xc3, 0x30,
	0x0c, 0x86, 0x51, 0x9b, 0xa4, 0x8d, 0xbb, 0xed, 0x60, 0xc6, 0x30, 0xec, 0x22, 0xc2, 0x0e, 0x3a,
	0xa5, 0x24, 0x2d, 0x7d, 0x80, 0x3e, 0x41, 0x11, 0x3b, 0xed, 0xd6, 0x6c, 0xde, 0x28, 0xa4, 0xf1,
	0x68, 0xdc, 0xc0, 0xde, 0x7c, 0xc7, 0x22, 0xdb, 0x3d, 0x59, 0xdf, 0x67, 0x5b, 0xe2, 0x97, 0x32,
	0xbf, 0x17, 0xe7, 0xdd, 0xda, 0xdb, 0xd1, 0xaf, 0xa7, 0x26, 0x9c, 0x75, 0x50, 0x7a, 0x11, 0xea,
	0xa9, 0xa9, 0xfe, 0x41, 0x65, 0xef, 0x76, 0xf4, 0xfa, 0x59, 0xe5, 0xa7, 0xc1, 0x6f, 0x5a, 0x03,
	0x08, 0x94, 0x73, 0x84, 0x64, 0x77, 0x5b, 0x33, 0x43, 0xa0, 0x39, 0x47, 0x10, 0xfb, 0xdd, 0xbb,
	0xa3, 0x37, 0x73, 0x04, 0x9a, 0x71, 0x04, 0xfd, 0xa2, 0x8a, 0x2f, 0x77, 0xed, 0x7a, 0x6b, 0x32,
	0x04, 0x02, 0x4e, 0x24, 0xfe, 0x1a, 0x5b, 0xe7, 0x08, 0xf4, 0xc8, 0x89, 0xee, 0x7e, 0xb7, 0x35,
	0x05, 0x02, 0x65, 0x9c, 0x48, 0x6b, 0x95, 0x75, 0xce, 0xf5, 0x66, 0x81, 0x40, 0x4b, 0x0e, 0xb5,
	0x4c, 0xec, 0xfe, 0xbc, 0x1d, 0xcd, 0x12, 0x81, 0x1e, 0x38, 0x82, 0x74, 0x18, 0xfd, 0xe5, 0x34,
	0xfc, 0x98, 0x12, 0x81, 0x4a, 0x4e, 0xa4, 0xdf, 0x54, 0x2e, 0xf9, 0x5a, 0xa3, 0x10, 0x68, 0xd5,
	0x3e, 0xd5, 0x29, 0x6d, 0x2d, 0x49, 0x5b, 0x8e, 0x97, 0xd5, 0xab, 0xca, 0x03, 0xcb, 0xc0, 0xe1,
	0x78, 0xb6, 0x21, 0x79, 0xc9, 0xa1, 0xde, 0x57, 0x6a, 0xf5, 0xe9, 0xce, 0xf7, 0x8f, 0xfb, 0x52,
	0x5e, 0x1e, 0x64, 0x75, 0x07, 0xf8, 0x28, 0xc4, 0x4e, 0x4d, 0x57, 0x84, 0x5d, 0x6e, 0x6e, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0xeb, 0xbc, 0x94, 0x67, 0x01, 0x00, 0x00,
}
